spring:
  application:
    name: blog
  profiles:
    active: local

server:
  port: 8081


---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:blog'
    username: baumblog
    password:

  h2:
    console:
      enabled: true
      path: /h2-blog

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: prod
